<?php
$z[0]=Array("langlist","\r\n      <a href=\"[field:typeurl/]\" title=\"[field:langname/]\">[field:langname/]</a>\r\n    ",274,393);
$z[1]=Array("global","",728,753);
$z[1][4]['name']="cfg_phpurl";
$z[2]=Array("handlang","",822,838);
$z[3]=Array("global","",1046,1071);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n<li><a href=\"[field:typelink/]\" class=\"one\"><span>[field:typename/]</span></a></li>\r\n",1106,1233);
$z[4][4]['type']="top";
$z[5]=Array("global","",4300,4329);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",4447,4476);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",4547,4576);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("mylang","",6712,6742);
$z[8][4]['eid']="huandeng";
$z[9]=Array("global","",6851,6880);
$z[9][4]['name']="cfg_templeturl";
$z[10]=Array("global","",6989,7018);
$z[10][4]['name']="cfg_templeturl";
$z[11]=Array("global","",7127,7156);
$z[11][4]['name']="cfg_templeturl";
$z[12]=Array("global","",7265,7294);
$z[12][4]['name']="cfg_templeturl";
$z[13]=Array("global","",7403,7432);
$z[13][4]['name']="cfg_templeturl";

?>