<?php
$z[0]=Array("langlist","\r\n      <a href=\"[field:typeurl/]\" title=\"[field:langname/]\">[field:langname/]</a>\r\n    ",274,393);
$z[1]=Array("global","",713,738);
$z[1][4]['name']="cfg_phpurl";
$z[2]=Array("handlang","",807,823);
$z[3]=Array("global","",1031,1056);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n<li><a href=\"[field:typelink/]\" class=\"one\"><span>[field:typename/]</span></a></li>\r\n",1091,1218);
$z[4][4]['type']="top";
$z[5]=Array("global","",4285,4314);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",4432,4461);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",4532,4561);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("mylang","",6697,6727);
$z[8][4]['eid']="huandeng";
$z[9]=Array("global","",6836,6865);
$z[9][4]['name']="cfg_templeturl";
$z[10]=Array("global","",6984,7013);
$z[10][4]['name']="cfg_templeturl";
$z[11]=Array("global","",7133,7162);
$z[11][4]['name']="cfg_templeturl";
$z[12]=Array("global","",7283,7312);
$z[12][4]['name']="cfg_templeturl";
$z[13]=Array("global","",7433,7462);
$z[13][4]['name']="cfg_templeturl";

?>